# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-21 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blog_readed_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='thumbnail_name',
            field=models.CharField(default='jump.jpg', max_length=15),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tag',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
