# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-21 14:30
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180921_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='thumbnail_name',
            field=models.CharField(default='0.jpg', max_length=15),
        ),
    ]
